### ISSUE TITLE
Context Manager gives ZeroDivisionError when no data is pushed

### ISSUE THREAD

**Issue by HarrisonMarcRose** [stitchdata/python-stitch-client#7]
An example would be 

```
def all_unicode_charadters():
    with Client(int([REDACTED]),
                "[REDACTED]",
                callback_function=print) as client:
        for index in range(sys.maxunicode):
            try:
                data = {
                    "table_name": "strings",
                    "sequence": int(1000000 * dt.now(tz=timezone.utc).timestamp()),
                    "action": "upsert",
                    "key_names": ["id"],
                    "data": {
                        "id": index,
                        "character": chr(index),
                    }
                }

                # client.push(data)
            except UnicodeEncodeError:
                pass
```

When the client.push(data) is commented out as above you get the following stack trace

```
Traceback (most recent call last):
  File "stitch_front_end_automation/tests/send_to_iapi_test.py", line 292, in <module>
    main()
  File "stitch_front_end_automation/tests/send_to_iapi_test.py", line 286, in main
    all_unicode_charadters()
  File "stitch_front_end_automation/tests/send_to_iapi_test.py", line 282, in all_unicode_charadters
    pass
  File "/home/vagrant/.virtualenvs/ui-automation/lib/python3.4/site-packages/stitchclient/client.py", line 188, in __exit__
    self.flush()
  File "/home/vagrant/.virtualenvs/ui-automation/lib/python3.4/site-packages/stitchclient/client.py", line 182, in flush
    self._send_batch(batch)
  File "/home/vagrant/.virtualenvs/ui-automation/lib/python3.4/site-packages/stitchclient/client.py", line 159, in _send_batch
    0.8 * (self.max_batch_size_bytes / self.moving_average_bytes_per_record()))
  File "/home/vagrant/.virtualenvs/ui-automation/lib/python3.4/site-packages/stitchclient/client.py", line 115, in moving_average_bytes_per_record
    return num_bytes // num_records
ZeroDivisionError: integer division or modulo by zero
```

**Comment by HarrisonMarcRose** [comment]
fixed with https://github.com/stitchdata/python-stitch-client/pull/8
